[template]
keys        = [ "app/server" ]
owner       = "nginx"
mode        = "0644"
src         = "nginx.conf.tmpl"
dest        = "/etc/nginx/sites-enabled/app.conf"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/usr/sbin/service nginx reload"


[template]
src   = "nginx.conf"
dest  = "/etc/nginx/nginx.conf"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "/nginx"
]
check_cmd  = "/app/bin/check {{ .src }}"
reload_cmd = "/usr/sbin/nginx -s reload"